tpm_luks: lots of updates
Signed-off-by: Kent Yoder <key@linux.vnet.ibm.com>

diff --git a/tpm_luks b/tpm_luks
--- a/tpm_luks
+++ b/tpm_luks
@@ -5,9 +5,11 @@
 # Author: Kent Yoder <yoder1@us.ibm.com>
 #
 CRYPTSETUP=/sbin/cryptsetup
-NV_INDEX_LIMIT=8
+NV_INDEX_LIMIT=16
+TPM_LUKS_NVRAM_SIZE=33
 
-#set -x
+set -e
+set -x
 function tpm_enabled
 {
 	if [ ! -e /sys/class/misc/tpm0/device/enabled ]; then
@@ -28,12 +30,44 @@ function tpm_enabled
 function tpm_owned
 {
 	if [ ! /sys/class/misc/tpm0/device/owned ]; then
-		echo "Your TPM is unowned, please take ownership:"
+		echo "Your TPM is unowned, please take ownership:\n"
 		tpm_takeownership || exit -1
 	fi
 
 	return 0
 }
+
+#
+# find_luks_nv_indexes - list defined NVRAM indexes that match the size we're
+#                        looking for
+#
+function find_luks_nv_indexes
+{
+	TMP_NVINFO=$(mktemp /tmp/${0##*/}-XXXXXX)
+	tpm_nvinfo >${TMP_NVINFO}
+
+	if [ $? -ne 0 ]; then
+		rm -f ${TMP_NVINFO}
+		exit -1
+	fi
+
+	NV_SIZES=( $(cat ${TMP_NVINFO} | awk '$1 ~ /Size/ { print $3 }') )
+	NV_INDEXES=( $(cat ${TMP_NVINFO} | awk '$1$2 ~ /NVRAMindex/ { print $4 }') )
+	NUM_INDEXES=$(cat ${TMP_NVINFO} | awk '$1$2 ~ /NVRAMindex/ { print $4 }' | wc -l)
+
+	NUM_INDEXES=$(( $NUM_INDEXES - 1 ))
+	for i in $(seq 0 ${NUM_INDEXES}); do
+		#echo "DBG: ${NV_SIZES[$i]}"
+		#echo "DBG: ${NV_INDEXES[$i]}"
+
+		if [ ${NV_SIZES[$i]} -eq ${TPM_LUKS_NVRAM_SIZE} ]; then
+			echo -n "${NV_INDEXES[$i]} "
+		fi
+	done
+
+	rm -f ${TMP_NVINFO}
+}
+
 
 function find_free_nv_index
 {
@@ -56,26 +90,17 @@ function find_luks_device
 
 	if [ $NUM_DEVS -eq 0 ]; then
 		echo "Couldn't find a LUKS mount!"
-		exit -1
-	elif [ $NUM_DEVS -gt 1 ]; then
-		echo "Found more than one LUKS mount!"
-		exit -1
+		return -1
+	elif [ $NUM_DEVS -ne 1 ]; then
+		echo "More than one LUKS device found, please specify a device with -d"
+		return -1
 	fi
 
 	echo "$(blkid -t TYPE=crypto_LUKS|awk -F: '{print $1}')"
 }
 
-#
-# nv_write <NV index> <tpm owner password> <new password for nv index>
-#
-function nv_write
+function keyfile_generate
 {
-	NVINDEX=${1}
-	DEVICE=${2}
-	OWNERPASS=${3}
-	NVPASS=${4}
-	PERMSFILE=${5}
-
 	TMPFS_MNT=$(mktemp -d /tmp/${0##*/}-XXXXXX)
 	mount -t tmpfs -o size=16K tmpfs ${TMPFS_MNT}
 	if [ $? -ne 0 ]; then
@@ -99,6 +124,17 @@ function nv_write
 		exit -1
 	fi
 
+	echo "${TMPFS_MNT}/key"
+}
+
+function nv_define_and_write
+{
+	OWNERPASS=${1}
+	NVPASS=${2}
+	DATAFILE=${3}
+	NVINDEX=${4}
+	PERMSFILE=${5}
+
 	if [ -n "${PERMSFILE}" ]; then
 		tpm_nvdefine -i ${NVINDEX} -s 33 -p 'AUTHREAD|AUTHWRITE' -o ${OWNERPASS} \
 			-a ${NVPASS} -f ${PERMSFILE}
@@ -108,21 +144,83 @@ function nv_write
 	fi
 
 	if [ $? -ne 0 ]; then
-		umount ${TMPFS_MNT}
-		exit -1
+		return -1
 	fi
 
-	tpm_nvwrite -i ${NVINDEX} -s 33 -f ${TMPFS_MNT}/key --password=${NVPASS}
+	tpm_nvwrite -i ${NVINDEX} -s 33 -f ${DATAFILE} --password=${NVPASS}
+	if [ $? -ne 0 ]; then
+		exit -1
+	fi
+}
+
+#
+# nv_write
+#
+function nv_write
+{
+	NVINDEX=${1}
+	DEVICE=${2}
+	OWNERPASS=${3}
+	NVPASS=${4}
+	PERMSFILE=${5}
+	KEY_SLOT=0
+
+#	TMPFS_MNT=$(mktemp -d /tmp/${0##*/}-XXXXXX)
+#	mount -t tmpfs -o size=16K tmpfs ${TMPFS_MNT}
+#	if [ $? -ne 0 ]; then
+#		echo "Unable to mount tmpfs area"
+#		exit -1
+#	fi
+#
+#	# write the version bytes (version 0)
+#	dd if=/dev/zero of=${TMPFS_MNT}/key bs=1c count=1 >/dev/null 2>&1
+#	if [ $? -ne 0 ]; then
+#		echo "dd failed"
+#		umount ${TMPFS_MNT}
+#		exit -1
+#	fi
+#
+#	# write a 32 byte symmetric key
+#	dd if=/dev/urandom of=${TMPFS_MNT}/key bs=1c seek=1 count=32 >/dev/null 2>&1
+#	if [ $? -ne 0 ]; then
+#		echo "dd failed"
+#		umount ${TMPFS_MNT}
+#		exit -1
+#	fi
+
+	TMPFS_KEYFILE=$(keyfile_generate)
+	TMPFS_MNT=${TMPFS_KEYFILE%/*}
+
+#	if [ -n "${PERMSFILE}" ]; then
+#		tpm_nvdefine -i ${NVINDEX} -s 33 -p 'AUTHREAD|AUTHWRITE' -o ${OWNERPASS} \
+#			-a ${NVPASS} -f ${PERMSFILE}
+#	else
+#		tpm_nvdefine -i ${NVINDEX} -s 33 -p 'AUTHREAD|AUTHWRITE' -o ${OWNERPASS} \
+#			-a ${NVPASS}
+#	fi
+#
+#	if [ $? -ne 0 ]; then
+#		umount ${TMPFS_MNT}
+#		exit -1
+#	fi
+#
+#	tpm_nvwrite -i ${NVINDEX} -s 33 -f ${TMPFS_KEYFILE} --password=${NVPASS}
+#	if [ $? -ne 0 ]; then
+#		umount ${TMPFS_MNT}
+#		exit -1
+#	fi
+
+	nv_define_and_write ${OWNERPASS} ${NVPASS} ${TMPFS_KEYFILE} ${NVINDEX} ${PERMSFILE}
 	if [ $? -ne 0 ]; then
 		umount ${TMPFS_MNT}
 		exit -1
 	fi
 
 	# copy out all but the version byte
-	dd if=${TMPFS_MNT}/key of=${TMPFS_MNT}/key.data bs=1c skip=1 count=32 >/dev/null 2>&1
+	dd if=${TMPFS_KEYFILE} of=${TMPFS_KEYFILE}.data bs=1c skip=1 count=32 >/dev/null 2>&1
 
 	SLOTID=0
-	for S in $(cryptsetup luksDump /dev/loop1| awk '$1$2 ~ /KeySlot/ {print $4}'); do
+	for S in $(cryptsetup luksDump ${DEVICE} | awk '$1$2 ~ /KeySlot/ {print $4}'); do
 		if [ "${S}" == "DISABLED" ]; then
 			KEY_SLOT=${SLOTID}
 			break
@@ -131,8 +229,9 @@ function nv_write
 	done
 
 	echo "You will now be prompted to enter any valid LUKS passphrase in order to store"
-	echo "the new TPM NVRAM secret in LUKS key slot ${KEY_SLOT}:"
-	$CRYPTSETUP luksAddKey --key-slot ${KEY_SLOT} $DEVICE ${TMPFS_MNT}/key.data
+	echo "the new TPM NVRAM secret in LUKS key slot ${KEY_SLOT}:\n"
+
+	$CRYPTSETUP luksAddKey --key-slot ${KEY_SLOT} $DEVICE ${TMPFS_KEYFILE}.data
 	if [ $? -ne 0 ]; then
 		tpm_nvrelease -i ${NVINDEX} -s 33 --pwdo=${OWNERPASS}
 		umount ${TMPFS_MNT}
@@ -140,23 +239,21 @@ function nv_write
 	fi
 
 	# zero the data we wrote to nvram (which includes the version byte) then rm it
-	dd if=/dev/zero of=${TMPFS_MNT}/key bs=33 count=1 >/dev/null 2>&1
-	rm -f ${TMPFS_MNT}/key
+	dd if=/dev/zero of=${TMPFS_KEYFILE} bs=33 count=1 >/dev/null 2>&1
+	rm -f ${TMPFS_KEYFILE}
 
 	# zero the key file and umount tmpfs
-	dd if=/dev/zero of=${TMPFS_MNT}/key.data bs=32 count=1 >/dev/null 2>&1
+	dd if=/dev/zero of=${TMPFS_KEYFILE}.data bs=32 count=1 >/dev/null 2>&1
 	umount ${TMPFS_MNT}
 }
 
 #
-# nv_retrieve <nv area password>
+# nv_get
 #
-function nv_retrieve
+function nv_get
 {
 	NVPASS=${1}
-	DEVICE=${2}
-	NAME=${3}
-	NVINDEX=1
+	NV_INDEXES=( $(find_luks_nv_indexes) )
 
 	TMPFS_MNT=$(mktemp -d /tmp/${0##*/}-XXXXXX)
 	mount -t tmpfs -o size=16K tmpfs ${TMPFS_MNT}
@@ -165,37 +262,79 @@ function nv_retrieve
 		exit -1
 	fi
 
-	while [ ${NVINDEX} -lt ${NV_INDEX_LIMIT} ]; do
-		tpm_nvread -i ${NVINDEX} -s 33 --password=${NVPASS} \
-			-f ${TMPFS_MNT}/data.tmp >/dev/null 2>&1
+	for i in ${NV_INDEXES[*]}; do
+		tpm_nvread -i $i -s 33 --password=${NVPASS} -f ${TMPFS_MNT}/data.tmp \
+			>/dev/null 2>&1
 		RC=$?
 		if [ ${RC} -ne 0 ]; then
-			NVINDEX=$(( $NVINDEX + 1 ))
-			echo "rc for tpm_nvread is ${RC}. Trying NV index ${NVINDEX}"
+			#echo "rc for tpm_nvread is ${RC} (ignoring). "
 			continue
 		fi
 
 		# version check
-		od -A n -N 1 -t x1 ${TMPFS_MNT}/data.tmp|grep -q 00
+		od -A n -N 1 -t x1 ${TMPFS_MNT}/data.tmp | grep -q 00
 		RC=$?
 		if [ ${RC} -ne 0 ]; then
-			echo "ignoring NV index ${NVINDEX} (wrong version)"
-			NVINDEX=$(( $NVINDEX + 1 ))
+			#echo "ignoring NV index ${NVINDEX} (wrong version)"
 			continue
 		fi
 
 		break
 	done
 
-	if [ ${NVINDEX} -eq ${NV_INDEX_LIMIT} ]; then
-		echo "Couldn't find a TPM NVRAM index containing a usable key, falling back"
-		echo "to password-based LUKS device opening."
-		$CRYPTSETUP luksOpen -T1 ${DEVICE} ${NAME}
-	fi
+	echo "${TMPFS_MNT}/data.tmp"
+}
+
+function luks_open
+{
+#
+# nv_retrieve
+#
+#function nv_retrieve
+#{
+#	NVPASS=${1}
+#	DEVICE=${2}
+#	NAME=${3}
+#	NVINDEX=1
+#
+#	TMPFS_MNT=$(mktemp -d /tmp/${0##*/}-XXXXXX)
+#	mount -t tmpfs -o size=16K tmpfs ${TMPFS_MNT}
+#	if [ $? -ne 0 ]; then
+#		echo "Unable to mount tmpfs area"
+#		exit -1
+#	fi
+#
+#	while [ ${NVINDEX} -lt ${NV_INDEX_LIMIT} ]; do
+#		tpm_nvread -i ${NVINDEX} -s 33 --password=${NVPASS} \
+#			-f ${TMPFS_MNT}/data.tmp >/dev/null 2>&1
+#		RC=$?
+#		if [ ${RC} -ne 0 ]; then
+#			NVINDEX=$(( $NVINDEX + 1 ))
+#			echo "rc for tpm_nvread is ${RC}. Trying NV index ${NVINDEX}"
+#			continue
+#		fi
+#
+#		# version check
+#		od -A n -N 1 -t x1 ${TMPFS_MNT}/data.tmp|grep -q 00
+#		RC=$?
+#		if [ ${RC} -ne 0 ]; then
+#			echo "ignoring NV index ${NVINDEX} (wrong version)"
+#			NVINDEX=$(( $NVINDEX + 1 ))
+#			continue
+#		fi
+#
+#		break
+#	done
+
+	TMPFS_FILE=${1}
+	DEVICE=${2}
+	NAME=${3}
+	TMPFS_MNT=${1%/*}
 
 	# copy out all but the version byte
-	dd if=${TMPFS_MNT}/data.tmp of=${TMPFS_MNT}/data bs=1c skip=1 count=32 >/dev/null 2>&1
-	rm -f ${TMPFS_MNT}/data.tmp
+	dd if=${TMPFS_FILE} of=${TMPFS_MNT}/data bs=1c skip=1 count=32 >/dev/null 2>&1
+	dd if=/dev/zero of=${TMPFS_FILE} bs=1c skip=1 count=33 >/dev/null 2>&1
+	rm -f ${TMPFS_FILE}
 
 	#echo "${TMPFS_MNT}/data"
 	$CRYPTSETUP luksOpen ${DEVICE} ${NAME} --key-file ${TMPFS_MNT}/data --keyfile-size 32 --readonly
@@ -207,18 +346,19 @@ function usage
 {
 	echo "usage ${0##*/}: [-c|-r] [options]"
 	echo "options:"
-	echo -e "  -c [NVPERMSFILE]  create a new key, store it in TPM NVRAM and add it to a"
+	echo -e "  -c                create a new key, store it in TPM NVRAM and add it to a"
 	echo -e	"                     LUKS keyslot"
-	echo -e "  -r <name>         retrieve a secret from TPM NVRAM and use it to open a "
-	echo -e	"                     LUKS device"
-	echo -e "  -d                re-use the same password for each NVRAM area (only prompt"
-	echo -e	"                     once)"
+	echo -e "  -o <name>         get a secret from TPM NVRAM and use it to open a LUKS device"
+#	echo -e "  -q                re-use the same password for each NVRAM area (only prompt"
+#	echo -e	"                     once)"
 	echo -e "  -s <keyslot>      use the specified LUKS key slot (view free slots with "
 	echo -e	"                     'cryptsetup luksDump <device>')"
-	echo -e "  -i <index>        use the specified TPM NVRAM index (view indexes with "
-	echo -e	"                     tpm_nvinfo)"
+	echo -e "  -i <index>        use the specified TPM NVRAM index for the new area (view "
+	echo -e	"                     indexes with tpm_nvinfo)"
 	echo -e "  -d <device>       use the specified LUKS device (print with "
 	echo -e	"                     'blkid -t TYPE=crypto_LUKS')"
+	echo -e "  -m                migrate NVRAM data to a new NVRAM area"
+	echo -e	"  -p <nvpermsfile>  use the specified NV permissions file for the new area"
 }
 
 #
@@ -235,90 +375,120 @@ NVPASS=
 NVINDEX=
 ACTION="xxx"
 
-while getopts "c:r:sd:q" opt; do
+while getopts "cp:ro:sd:qm" opt; do
 	case $opt in
-		c)
-			ACTION="create"
-			PERMSFILE=${OPTARG}
-			;;
-		r)
-			ACTION="retrieve"
-			NAME=${OPTARG}
-			;;
-		s)
-			KEY_SLOT=${OPTARG}
-			;;
-		i)
-			NVINDEX=${OPTARG}
-			;;
-		d)
-			DEVICE=${OPTARG}
-			;;
-		q)
-			SAME_AUTH=1
-			;;
-		*)
-			usage
-			;;
+	c)
+		ACTION="create"
+		;;
+	o)
+		ACTION="open"
+		NAME=${OPTARG}
+		;;
+	s)
+		KEY_SLOT=${OPTARG}
+		;;
+	i)
+		NVINDEX=${OPTARG}
+		;;
+	d)
+		DEVICE=${OPTARG}
+		;;
+	p)
+		PERMSFILE=${OPTARG}
+		;;
+	q)
+		SAME_AUTH=1
+		;;
+	m)
+		ACTION="migrate"
+		;;
+	r)
+		ACTION="retrieve"
+		;;
+	*)
+		usage
+		exit -1
+		;;
 	esac
 done
 
-if [ "${ACTION}" == "create" ]; then
-	OWNERPASS=
+# always check that TPM is enabled and owned
+tpm_enabled
+tpm_owned
 
-	if [ -n "${PERMSFILE}" ]; then
-		if [ ! -e "${PERMSFILE}" ]; then
-			echo "Error: couldn't open ${PERMSFILE} for reading."
-			exit -1
-		fi
+if [ "${ACTION}" == "create" ]; then
+	if [ -n "${PERMSFILE}" -a ! -e "${PERMSFILE}" ]; then
+		echo "Error: couldn't open ${PERMSFILE} for reading."
+		exit -1
 	fi
 
-	tpm_enabled
-	tpm_owned
-
-	DEVICES=$(find_luks_device)
+	DEVICE=$(find_luks_device)
 
 	if [ ! -n "${OWNERPASS}" ]; then
 		read -s -p "Enter your TPM owner password: " OWNERPASS
 		echo
 	fi
 
-	# we can't seal multiple scerets in a single NV index
-	if [ -n "${NVINDEX}"  -a $(cat ${DEVICES}|wc -w) -ne 1 ]; then
-		echo "Multiple LUKS devices found, please pick one"
-		exit 2
+	if [ ! -n "${NVINDEX}" ]; then
+		NVINDEX=$(find_free_nv_index)
 	fi
 
-	for DEVICE in ${DEVICES}; do
-		NV_INDEX=$(find_free_nv_index)
+	echo "Using NV index ${NVINDEX} for device ${DEVICE}"
 
-		echo "Using NV index ${NV_INDEX} for device ${DEVICE}"
+	if [ ! -n "NVPASS1" -o ${SAME_AUTH} -eq 0 ]; then
+		read -s -p "Enter a TPM NV area password for ${DEVICE}: " NVPASS1
+		echo
+		read -s -p "Re-enter a TPM NV area password for ${DEVICE}: " NVPASS2
+		echo
 
-		if [ ! -n "NVPASS1" -o ${SAME_AUTH} -eq 0 ]; then
-			read -s -p "Enter a TPM NV area password for ${DEVICE}: " NVPASS1
-			echo
-			read -s -p "Re-enter a TPM NV area password for ${DEVICE}: " NVPASS2
-			echo
-
-			if [ "${NVPASS1}" != "${NVPASS2}" ]; then
-				echo "NV passwords don't match!"
-				exit -1
-			fi
+		if [ "${NVPASS1}" != "${NVPASS2}" ]; then
+			echo "NV passwords don't match!"
+			exit -1
 		fi
+	fi
 
-		nv_write ${NV_INDEX} ${DEVICE} ${OWNERPASS} ${NVPASS1} ${PERMSFILE}
-	done
-elif [ "${ACTION}" == "retrieve" ]; then
-	NVPASS=
-	DEVICE=${1}
-	NAME=${2}
-
+	nv_write ${NVINDEX} ${DEVICE} ${OWNERPASS} ${NVPASS1} ${PERMSFILE}
+elif [ "${ACTION}" == "open" ]; then
 	if [ ! -n "${NVPASS}" ]; then
 		read -s -p "Enter your TPM NVRAM password: " NVPASS
 		echo
 	fi
 
-	nv_retrieve ${NVPASS} ${DEVICE} ${NAME}
+	if [ ! -n "${DEVICE}" ]; then
+		DEVICES=$(find_luks_device)
+		if [ -n "${DEVICES}" ]; then
+			exit 3
+		fi
+		DEVICE=${DEVICES}
+	fi
+
+	NVFILE=$(nv_get ${NVPASS})
+	luks_open ${NVFILE} ${DEVICE} ${NAME}
+
+elif [ "${ACTION}" == "migrate" ]; then
+	if [ ! -n "${OWNERPASS}" ]; then
+		read -s -p "Enter your TPM owner password: " OWNERPASS
+		echo
+	fi
+
+	if [ ! -n "${NVPASS}" ]; then
+		read -s -p "Enter your current TPM NVRAM password: " NVPASS
+		echo
+	fi
+
+	if [ ! -n "${NVINDEX}" ]; then
+		NVINDEX=$(find_free_nv_index)
+	fi
+
+	NVFILE=$(nv_get ${NVPASS})
+	nv_define_and_write ${OWNERPASS} ${NVPASS} ${NVFILE} ${NVINDEX} ${PERMSFILE}
+elif [ "${ACTION}" == "retrieve" ]; then
+	if [ ! -n "${NVPASS}" ]; then
+		read -s -p "Enter your current TPM NVRAM password: " NVPASS
+		echo
+	fi
+
+	echo $(nv_get ${NVPASS})
 else
 	usage
 	exit 1
