tpm-luks: move tmpfs mount to /dev/shm
Signed-off-by: Kent Yoder <key@linux.vnet.ibm.com>

diff --git a/tpm-luks/tpm-luks b/tpm-luks/tpm-luks
--- a/tpm-luks/tpm-luks
+++ b/tpm-luks/tpm-luks
@@ -52,10 +52,11 @@ function get_owner_password
 	fi
 }
 
-function exit_hook
-{
-	umount $TMPFS_MNT
-}
+# XXX
+#function exit_hook
+#{
+#	umount $TMPFS_MNT
+#}
 
 function wipe_file
 {
@@ -65,24 +66,25 @@ function wipe_file
 
 function create_tmpfs_mount
 {
-	test -n "$TMPFS_MNT" && echo "BUG IN SCRIPT MULTIPLE TEMP MOUNTS" && exit 4
+	#test -n "$TMPFS_MNT" && echo "BUG IN SCRIPT MULTIPLE TEMP MOUNTS" && exit 4
 
-	TMPFS_MNT=$(mktemp -q -d /tmp/${0##*/}-XXXXXX)
-	if [ -n "$TMPFS_MNT" ]; then
-		mount -t tmpfs -o size=16K tmpfs ${TMPFS_MNT}
-
-		if [ $? -eq 0 ]; then
-			if [ ${1} -eq 1 ]; then
-				trap exit_hook EXIT
-			fi
-		else
-			# let the output from mount tell the user what happened
-			exit 5
-		fi
-	else
-		echo "Failed to create temp mount point for tmpfs"
-		exit 6
-	fi
+	#TMPFS_MNT=$(mktemp -q -d /tmp/${0##*/}-XXXXXX)
+	#if [ -n "$TMPFS_MNT" ]; then
+	#	mount -t tmpfs -o size=16K tmpfs ${TMPFS_MNT}
+	#
+	#	if [ $? -eq 0 ]; then
+	#		if [ ${1} -eq 1 ]; then
+	#			trap exit_hook EXIT
+	#		fi
+	#	else
+	#		# let the output from mount tell the user what happened
+	#		exit 5
+	#	fi
+	#else
+	#	echo "Failed to create temp mount point for tmpfs"
+	#	exit 6
+	#fi
+	TMPFS_MNT="/dev/shm"
 }
 
 function tpm_enabled
@@ -288,7 +290,7 @@ function nv_get
 	done
 
 	dd if=/dev/zero of=${TMPFS_KEYFILE} bs=1c count=33 >/dev/null 2>&1
-	umount ${TMPFS_MNT}
+	#umount ${TMPFS_MNT}
 	echo "Couldn't read any indexes from TPM NVRAM"
 	exit 18
 }
@@ -296,7 +298,7 @@ function nv_get
 function luks_open
 {
 	NAME=${1}
-	TMPFS_MNT=${TMPFS_KEYFILE%/*}
+	#TMPFS_MNT=${TMPFS_KEYFILE%/*}
 
 	# copy out all but the version byte to a new file
 	dd if=${TMPFS_KEYFILE} of=${TMPFS_MNT}/data bs=1c skip=1 count=32 >/dev/null 2>&1
@@ -363,7 +365,7 @@ function usage
 #
 # main()
 #
-UIDCHECK=1
+#UIDCHECK=1
 NVINDEX=
 ACTION="x"
 
@@ -387,7 +389,7 @@ while getopts "kco:mrw:s:i:d:p:qh" opt; do
 		;;
 	w)
 		[[ "${ACTION}" == "x" ]] && ACTION="write" || (usage && exit 255)
-		UIDCHECK=0
+		#UIDCHECK=0
 		TMPFS_KEYFILE=${OPTARG}
 		;;
 	s)
@@ -415,10 +417,10 @@ while getopts "kco:mrw:s:i:d:p:qh" opt; do
 done
 
 
-if [ ${UIDCHECK} -a $(id -u) -ne 0 ]; then
-	echo "You'll need to be root for this (uses tmpfs mount)"
-	exit 22
-fi
+#if [ ${UIDCHECK} -a $(id -u) -ne 0 ]; then
+#	echo "You'll need to be root for this (uses tmpfs mount)"
+#	exit 22
+#fi
 
 # always check that TPM is enabled and owned
 tpm_enabled
@@ -449,14 +451,14 @@ elif [ "${ACTION}" == "open" ]; then
 	nv_get
 	luks_open ${NAME}
 	wipe_file ${TMPFS_KEYFILE}
-	exit_hook
+	#exit_hook
 elif [ "${ACTION}" == "migrate" ]; then
 	nv_get
 	NVINDEX=""
 	nv_define_and_write ${PERMSFILE}
 
 	wipe_file ${TMPFS_KEYFILE}
-	exit_hook
+	#exit_hook
 elif [ "${ACTION}" == "retrieve" ]; then
 	nv_get
 	echo ${TMPFS_KEYFILE}
@@ -473,7 +475,7 @@ elif [ "${ACTION}" == "kill" ]; then
 	nv_get
 	luks_kill
 	wipe_file ${TMPFS_KEYFILE}
-	exit_hook
+	#exit_hook
 else
 	usage
 	exit 1
