tpm_luks: add kill option
Signed-off-by: Kent Yoder <key@linux.vnet.ibm.com>

diff --git a/tpm-luks/tpm_luks b/tpm-luks/tpm_luks
--- a/tpm-luks/tpm_luks
+++ b/tpm-luks/tpm_luks
@@ -17,6 +17,7 @@ TMPFS_KEYFILE=
 SCRIPT_RC=0
 OWNERPASS=
 NVPASS=
+KEY_SLOT=
 
 function prompt_for_new_nvpass
 {
@@ -28,7 +29,7 @@ function prompt_for_new_nvpass
 
 		if [ "${NVPASS1}" != "${NVPASS2}" ]; then
 			echo "New passwords don't match!"
-			exit -1
+			exit 1
 		fi
 
 		NVPASS=${NVPASS1}
@@ -38,7 +39,7 @@ function prompt_for_new_nvpass
 function get_nv_password
 {
 	if [ ! -n "${NVPASS}" ]; then
-		read -s -p "Enter your current TPM NVRAM password: " NVPASS || exit -1
+		read -s -p "Enter your current TPM NVRAM password: " NVPASS || exit 2
 		echo
 	fi
 }
@@ -46,7 +47,7 @@ function get_nv_password
 function get_owner_password
 {
 	if [ ! -n "${OWNERPASS}" ]; then
-		read -s -p "Enter your TPM owner password: " OWNERPASS || exit -1
+		read -s -p "Enter your TPM owner password: " OWNERPASS || exit 3
 		echo
 	fi
 }
@@ -64,7 +65,7 @@ function wipe_file
 
 function create_tmpfs_mount
 {
-	test -n "$TMPFS_MNT" && echo "BUG IN SCRIPT MULTIPLE TEMP MOUNTS" && exit -1
+	test -n "$TMPFS_MNT" && echo "BUG IN SCRIPT MULTIPLE TEMP MOUNTS" && exit 4
 
 	TMPFS_MNT=$(mktemp -q -d /tmp/${0##*/}-XXXXXX)
 	if [ -n "$TMPFS_MNT" ]; then
@@ -76,11 +77,11 @@ function create_tmpfs_mount
 			fi
 		else
 			# let the output from mount tell the user what happened
-			exit -1
+			exit 5
 		fi
 	else
 		echo "Failed to create temp mount point for tmpfs"
-		exit -1
+		exit 6
 	fi
 }
 
@@ -89,13 +90,13 @@ function tpm_enabled
 	if [ ! -e /sys/class/misc/tpm0/device/enabled ]; then
 		echo "Your TPM device driver doesn't appear to be loaded. Please run"
 		echo "\`modprobe tpm_tis\` to load the driver and re-run this script"
-		exit -1
+		exit 7
 	fi
 
 	if [ ! /sys/class/misc/tpm0/device/enabled ]; then
 		echo "Your TPM is not enabled in your BIOS. Please halt the machine and"
 		echo "then cold boot into your BIOS to enable the TPM chip."
-		exit -1
+		exit 8
 	fi
 
 	return 0
@@ -105,7 +106,7 @@ function tpm_owned
 {
 	if [ $(cat /sys/class/misc/tpm0/device/owned) -ne 1 ]; then
 		echo "Your TPM is unowned, please take ownership:"
-		tpm_takeownership || exit -1
+		tpm_takeownership || exit 9
 	fi
 
 	return 0
@@ -157,16 +158,16 @@ function find_luks_device
 
 	if [ $NUM_DEVS -eq 0 ]; then
 		echo "Couldn't find a LUKS mount!"
-		exit -1
+		exit 10
 	elif [ $NUM_DEVS -gt 1 ]; then
 		echo "Found more than one LUKS mount, use -d option"
-		exit -1
+		exit 11
 	fi
 
 	DEVICE="$(blkid -t TYPE=crypto_LUKS|${AWK} -F: '{print $1}')"
 	if [ $? -ne 0 ]; then
 		DEVICE=
-		exit -1
+		exit 12
 	fi
 
 	return 0
@@ -191,11 +192,11 @@ function keyfile_generate
 
 	# write the version bytes (version 0)
 	dd if=/dev/zero of=${TMPFS_KEYFILE} bs=1c count=1 >/dev/null 2>&1 \
-		|| exit -1
+		|| exit 13
 
 	# write a 32 byte symmetric key
 	dd if=/dev/urandom of=${TMPFS_KEYFILE} bs=1c seek=1 count=32 \
-		>/dev/null 2>&1 || exit -1
+		>/dev/null 2>&1 || exit 14
 }
 
 function nv_define_and_write
@@ -218,13 +219,13 @@ function nv_define_and_write
 	fi
 
 	if [ $? -ne 0 ]; then
-		return 255
+		return 15
 	fi
 
 	tpm_nvwrite -i ${NVINDEX} -s 33 -f ${DATAFILE} --password=${NVPASS}
 	if [ $? -ne 0 ]; then
 		tpm_nvrelease -i ${NVINDEX} --pwdo=${OWNERPASS}
-		return 255
+		return 16
 	fi
 
 	return 0
@@ -271,7 +272,7 @@ function nv_get
 
 	if [ ${#NV_INDEXES} -eq 0 ]; then
 		echo "Found 0 NVRAM indexes readable by this script"
-		exit -1
+		exit 17
 	fi
 
 	create_tmpfs_mount 0
@@ -289,7 +290,7 @@ function nv_get
 	dd if=/dev/zero of=${TMPFS_KEYFILE} bs=1c count=33 >/dev/null 2>&1
 	umount ${TMPFS_MNT}
 	echo "Couldn't read any indexes from TPM NVRAM"
-	exit -1
+	exit 18
 }
 
 function luks_open
@@ -299,6 +300,12 @@ function luks_open
 
 	# copy out all but the version byte to a new file
 	dd if=${TMPFS_KEYFILE} of=${TMPFS_MNT}/data bs=1c skip=1 count=32 >/dev/null 2>&1
+	if [ $? -ne 0 ]; then
+		echo "dd failed! exiting..."
+		wipe_file ${TMPFS_MNT}/data
+		SCRIPT_RC=19
+		return
+	fi
 
 	$CRYPTSETUP luksOpen ${DEVICE} ${NAME} --key-file ${TMPFS_MNT}/data --keyfile-size 32
 	SCRIPT_RC=$?
@@ -306,15 +313,41 @@ function luks_open
 	wipe_file ${TMPFS_MNT}/data
 }
 
+#
+# luks_kill - call cryptsetup luksKillSlot
+#
+# @TMPFS_KEYFILE - the NVRAM data to extract the key from
+# @DEVICE - the LUKS device
+# @KEY_SLOT - the slot to kill
+#
+function luks_kill
+{
+	TMPFS_MNT=${TMPFS_KEYFILE%/*}
+	TMPFS_KEY=${TMPFS_MNT}/key
+
+	dd if=${TMPFS_KEYFILE} of=${TMPFS_KEY} bs=1c skip=1 count=32 >/dev/null 2>&1
+	if [ $? -ne 0 ]; then
+		echo "dd failed! exiting..."
+		wipe_file ${TMPFS_KEY}
+		SCRIPT_RC=20
+		return
+	fi
+
+	$CRYPTSETUP luksKillSlot ${DEVICE} ${KEY_SLOT} --key-file ${TMPFS_KEY} --keyfile-size 32
+	SCRIPT_RC=$?
+	wipe_file ${TMPFS_KEY}
+}
+
 function usage
 {
-	echo "usage ${0##*/}: [-c|-o|-m|-r|-w] [options]"
+	echo "usage ${0##*/}: [-c|-o|-m|-r|-w|-k] [options]"
 	echo -e "  -c                create a new key, store it in TPM NVRAM and add it to a"
 	echo -e	"                     LUKS keyslot"
 	echo -e "  -o <name>         get a secret from TPM NVRAM and use it to open a LUKS device"
 	echo -e "  -m                migrate NVRAM data to a new NVRAM area"
 	echo -e "  -r                retrieve NVRAM data and write to a tmpfs file"
 	echo -e "  -w <file>         write file to NVRAM"
+	echo -e "  -k                kill a LUKS key slot using a key file read from NVRAM"
 	echo
 	echo "options:"
 	echo -e "  -s <keyslot>      use the specified LUKS key slot (view free slots with "
@@ -334,23 +367,26 @@ UIDCHECK=1
 NVINDEX=
 ACTION="x"
 
-while getopts "co:mrw:s:i:d:p:qh" opt; do
+while getopts "kco:mrw:s:i:d:p:qh" opt; do
 	case $opt in
+	k)
+		[[ ${ACTION} = "x" ]] && ACTION="kill" || usage && exit 255
+		;;
 	c)
-		ACTION="create"
+		[[ ${ACTION} = "x" ]] && ACTION="create" || usage && exit 255
 		;;
 	o)
-		ACTION="open"
+		[[ ${ACTION} = "x" ]] && ACTION="open" || usage && exit 255
 		NAME=${OPTARG}
 		;;
 	m)
-		ACTION="migrate"
+		[[ ${ACTION} = "x" ]] && ACTION="migrate" || usage && exit 255
 		;;
 	r)
-		ACTION="retrieve"
+		[[ ${ACTION} = "x" ]] && ACTION="retrieve" || usage && exit 255
 		;;
 	w)
-		ACTION="write"
+		[[ ${ACTION} = "x" ]] && ACTION="write" || usage && exit 255
 		UIDCHECK=0
 		TMPFS_KEYFILE=${OPTARG}
 		;;
@@ -365,10 +401,15 @@ while getopts "co:mrw:s:i:d:p:qh" opt; do
 		;;
 	p)
 		PERMSFILE=${OPTARG}
+
+		if [ -n "${PERMSFILE}" -a ! -e "${PERMSFILE}" ]; then
+			echo "Error: couldn't open ${PERMSFILE} for reading."
+			exit 21
+		fi
 		;;
 	*)
 		usage
-		exit -1
+		exit 255
 		;;
 	esac
 done
@@ -376,7 +417,7 @@ done
 
 if [ ${UIDCHECK} -a $(id -u) -ne 0 ]; then
 	echo "You'll need to be root for this (uses tmpfs mount)"
-	exit -1
+	exit 22
 fi
 
 # always check that TPM is enabled and owned
@@ -384,20 +425,14 @@ tpm_enabled
 tpm_owned
 
 if [ "${ACTION}" == "create" ]; then
-	if [ -n "${PERMSFILE}" -a ! -e "${PERMSFILE}" ]; then
-		echo "Error: couldn't open ${PERMSFILE} for reading."
-		exit -1
-	fi
-
 	device_get
-
 	prompt_for_new_nvpass
-
 	keyfile_generate
 
 	nv_define_and_write ${PERMSFILE}
-	if [ $? -ne 0 ]; then
-		exit -1
+	RC=$?
+	if [ $RC -ne 0 ]; then
+		exit $RC
 	fi
 
 	# copy out all but the version byte
@@ -428,6 +463,16 @@ elif [ "${ACTION}" == "retrieve" ]; then
 elif [ "${ACTION}" == "write" ]; then
 	prompt_for_new_nvpass
 	nv_define_and_write ${PERMSFILE}
+elif [ "${ACTION}" == "kill" ]; then
+	if [ ! -n "${KEY_SLOT}" ]; then
+		echo "Kill requires the -s option to specify a LUKS key slot"
+		exit 255
+	fi
+
+	device_get
+	nv_get
+	luks_kill
+	wipe_file ${TMPFS_KEYFILE}
 else
 	usage
 	exit 1
